Remove adding symlink

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -10,21 +10,44 @@ on:
 
 jobs:
   check_code_style:
-    runs-on: macos-latest
-    #runs-on: ${{ matrix.os }}
-    #strategy:
-    #  matrix:
-    #    os: [ubuntu-latest]
-    #    version: [12]
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         with:
           submodules: 'true'
+
+      - name: Check for clang-format
+        run: |
+          which clang-format >/dev/null
+          if [[ $? != 0 ]]; then
+            printf "Failed to find 'clang-format' (please install it)\n"
+            exit 1
+          fi
+
+
+      # IMPORTANT NOTE
+      # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
+      # If you check the link above you will see that on Ubuntu 20.04
+      # we have preinstalled clang-format-10/11/12. By default the symlink
+      # to /usr/bin/clang-format-11 is set. That's why we will not be able
+      # to run successfully the checks for code style cause the minimum
+      # version required is `12` (see `dev-tools/check-code-style/check_style.sh` 
+      # especially check_clang_format() function).
+      # That's why the main idea of this step is just setting the symlink to
+      # /usr/bin/clang-format-12, nothing more. Thus we will be able to run all
+      # checks with correct version of clang-format using GitHub Actions. 
+      - name: Create symlink to /usr/bin/clang-format-12
+        run: |
+          # Before we recreate the symlink we should delete
+          # the existing one.
+          sudo rm /etc/alternatives/clang-format
+
+          # Recreate symlink 'clang-format'
+          sudo ln -s /usr/bin/clang-format-12 /etc/alternatives/clang-format 
+        shell: bash  
 
       # Call the composite action to check files
       # for correct code style. This action (action.yml)
       # is in `3rdparty/dev-tools/check-code-style` submodule's
       # directory.
       - uses: ArthurBandaryk/dev-tools/check-code-style@main
-        with:
-          clang-format-version: '12'
